client localhost {
    ipaddr = 127.0.0.1
    secret = testing123
    require_message_authenticator = no
    nastype = other
}

client zt_network {
    ipaddr = 192.168.200.20/32
    secret = zt_secret
    require_message_authenticator = no
    nastype = other
} 