services:
  client-service:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "5000:5000"
    env_file:
      - .env.client
    networks:
      - keycloak-network

  pep-service:
    build:
      context: .
      dockerfile: Dockerfile.pep
    ports:
      - "5001:5001"
    env_file:
      - .env.pep
    networks:
      - keycloak-network
    depends_on:
      - pdp-service

  pdp-service:
    build:
      context: .
      dockerfile: Dockerfile.pdp
    ports:
      - "5002:5002"
    env_file:
      - .env.pdp
    networks:
      - keycloak-network

  protected-resource:
    build:
      context: .
      dockerfile: Dockerfile.protected
    ports:
      - "5003:5003"
    env_file:
      - .env.protected
    networks:
      - keycloak-network
    depends_on:
      - pep-service

networks:
  keycloak-network:
    external: true
    name: keycloak-docker_keycloak-network