version: '3.8'

services:
  client-service:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "5000:5000"
    environment:
      - KEYCLOAK_HOST=localhost
      - KEYCLOAK_PORT=8080
      - REALM=zta
      - CLIENT_ID=pep-backend
      - PDP_HOST=pdp-service
      - PDP_PORT=5002
      - RESOURCE_HOST=protected-resource
      - RESOURCE_PORT=8000
      - PEP_HOST=pep-service
      - PEP_PORT=5003
      - CLIENT_SECRET=DXtmD2csJMM21EcTbOXWoFqNRF5yvGS2
    networks:
      - zta-network
      - protected-network

  pep-service:
    build:
      context: .
      dockerfile: Dockerfile.pep
    expose:
      - "5003"
    environment:
      - KEYCLOAK_HOST=localhost
      - KEYCLOAK_PORT=8080
      - REALM=zta
      - CLIENT_ID=pep-backend
      - RESOURCE_HOST=protected-resource
      - RESOURCE_PORT=8000
    networks:
      - zta-network
      - protected-network
    depends_on:
      - pdp-service

  pdp-service:
    build:
      context: .
      dockerfile: Dockerfile.pdp
    expose:
      - "5002"
    environment:
      - KEYCLOAK_HOST=localhost
      - KEYCLOAK_PORT=8080
      - REALM=zta
      - CLIENT_ID=pep-backend
      - PEP_HOST=pep-service
      - PEP_PORT=5003
    networks:
      - zta-network
      - protected-network

  portknock:
    build:
      context: .
      dockerfile: Dockerfile.portknock
    expose:
      - "7000-9000"
    environment:
      - KNOCK_SEQUENCE=7000,8000,9000
      - KNOCK_TIMEOUT=10
      - PORT_OPEN_DURATION=30
      - PROTECTED_PORTS=5001,5002,5003,8080,8000
    networks:
      - zta-network
      - protected-network

networks:
  zta-network:
    driver: bridge
  protected-network:
    external: true
    name: protected_resource_protected-network
